Recipe.create!([
  {title: "서리태 냉콩국수", url: "http://haemukja.com/recipes/696", image: "http://cloudfront.haemukja.com/vh.php?url=http://d1hk7gw6lgygff.cloudfront.net/uploads/direction/image_file/8028/pad_thumb_DSC07520.JPG&convert=jpgmin&rt=600", writer: "로즈", subtitle: "여름철별미 서리태 냉콩국수"},
  {title: "콩국수", url: "http://haemukja.com/recipes/697", image: "http://cloudfront.haemukja.com/vh.php?url=http://d1hk7gw6lgygff.cloudfront.net/uploads/direction/image_file/8039/pad_thumb_12.jpg&convert=jpgmin&rt=600", writer: "살림의여신", subtitle: "콩국물로 만드는 간편한 여름별미  만들기~ 콩국수"},
  {title: "콩국수", url: "http://haemukja.com/recipes/693", image: "http://cloudfront.haemukja.com/vh.php?url=http://d1hk7gw6lgygff.cloudfront.net/uploads/direction/image_file/7999/pad_thumb_1.jpg&convert=jpgmin&rt=600", writer: "햇살한스푼", subtitle: "여름별미  만드는법~ 콩국수"},
  {title: "스토로베리 요거트 아이스캔디", url: "http://haemukja.com/recipes/572", image: "http://cloudfront.haemukja.com/vh.php?url=http://d1hk7gw6lgygff.cloudfront.net/uploads/direction/image_file/6631/pad_thumb_IMG_3471-1024x682.jpg&convert=jpgmin&rt=600", writer: "해먹남녀", subtitle: "여름을 기다리는 스트로베리 요거트 아이스캔디 스토로베리 요거트 아이스캔디"},
  {title: "유자 스파클링 칵테일", url: "http://haemukja.com/recipes/888", image: "http://cloudfront.haemukja.com/vh.php?url=http://d1hk7gw6lgygff.cloudfront.net/uploads/direction/image_file/12072/pad_thumb_____.jpg&convert=jpgmin&rt=600", writer: "해먹남녀", subtitle: "한여름밤의 수다: 유자 스파클링 칵테일"},
  {title: "수박국수", url: "http://haemukja.com/recipes/2976", image: "", writer: "해먹남녀", subtitle: "더위야~언제 물러갈래? 남은 더위 날려주는 이색 !! 수박국수"},
  {title: "죠스바에이드", url: "http://haemukja.com/recipes/4907", image: "http://cloudfront.haemukja.com/vh.php?url=http://d1hk7gw6lgygff.cloudfront.net/uploads/direction/image_file/58268/pad_thumb_1.jpg&convert=jpgmin&rt=600", writer: "해먹남녀", subtitle: "상어~ 상어상어! 죠스바에이드"},
  {title: "오이냉메밀국수", url: "http://haemukja.com/recipes/1139", image: "http://cloudfront.haemukja.com/vh.php?url=http://d1hk7gw6lgygff.cloudfront.net/uploads/direction/image_file/16688/pad_thumb_11.jpg&convert=jpgmin&rt=600", writer: "해먹남녀", subtitle: "여름아 맛있게 안녕! 오이냉메밀국수"},
  {title: "대패 삼겹살 냉채", url: "http://haemukja.com/recipes/904", image: "http://cloudfront.haemukja.com/vh.php?url=http://d1hk7gw6lgygff.cloudfront.net/uploads/direction/image_file/12078/pad_thumb_____.jpg&convert=jpgmin&rt=600", writer: "해먹남녀", subtitle: "무더운 여름날, 힘 빠지는 월요일 기운 돋우는 레시피 : 대패 삼겹살 냉채"}
])
