Recipe.create!([
  {title: "서리태 냉콩국수", url: "http://haemukja.com/recipes/696", image: "http://cloudfront.haemukja.com/vh.php?url=http://d1hk7gw6lgygff.cloudfront.net/uploads/direction/image_file/8028/pad_thumb_DSC07520.JPG&convert=jpgmin&rt=600", writer: "로즈", subtitle: "여름철별미 서리태 냉콩국수", serving: "1인 기준", recipe_material: "검정콩서리태 한대접, 오이 , 방울토마토 3개, 계란 1개, 검은깨 , 현미국수 , 얼음 , 소금 ", missed_material: "검정콩서리태 한대접, 현미국수 "},
  {title: "홍구리라면", url: "http://haemukja.com/recipes/500", image: "http://cloudfront.haemukja.com/vh.php?url=http://d1hk7gw6lgygff.cloudfront.net/uploads/direction/image_file/5830/pad_thumb_DSC01506.JPG&convert=jpgmin&rt=600", writer: "로즈", subtitle: "홍석천 홍구리 ♡ 해투 야간매점", serving: "1인 기준", recipe_material: "물 300ml, 라면 1개, 청량고추 1개, 치즈 1개", missed_material: "청량고추 1개"},
  {title: "유자 스파클링 칵테일", url: "http://haemukja.com/recipes/888", image: "http://cloudfront.haemukja.com/vh.php?url=http://d1hk7gw6lgygff.cloudfront.net/uploads/direction/image_file/12072/pad_thumb_____.jpg&convert=jpgmin&rt=600", writer: "해먹남녀", subtitle: "한여름밤의 수다: 유자 스파클링 칵테일", serving: "2인 기준", recipe_material: "유자청 3큰술, 스파클링와인 100mL, 레몬즙 45mL, 애플민트 8줄기, 레몬슬라이스 2장, 애플민트 2대, 얼음 약간", missed_material: "스파클링와인 100mL, 레몬슬라이스 2장"},
  {title: "동파육", url: "http://haemukja.com/recipes/2753", image: "", writer: "해먹남녀", subtitle: "풍미가 가득한 삼겹살 요리, 동파육", serving: "2인 기준", recipe_material: "삼겹살 600g, 마늘 100g, 양파 1개, 대파 1개, 통후추 1/2큰술, 진간장 100ml, 양조간장 50ml, 맛술 150ml, 설탕 1큰술, 청경채 1컵", missed_material: "통후추 1/2큰술, 맛술 150ml"},
  {title: "수박냉면", url: "http://haemukja.com/recipes/972", image: "http://cloudfront.haemukja.com/vh.php?url=http://d1hk7gw6lgygff.cloudfront.net/uploads/direction/image_file/13152/pad_thumb___.JPG&convert=jpgmin&rt=600", writer: "해먹남녀", subtitle: "수박으로 냉면을 만든다고? : 여름별미 중의 별미, 수박냉면", serving: "2인 기준", recipe_material: "수박 1/2통, 냉면사리 2인분, 삶은달걀 1개, 오이 1/2개, 양상추 1/4통, 고추가루 5숟갈, 식초 50mL, 물엿 3숟갈, 간장 2숟갈, 깨소금 2꼬집, 참기름 1숟갈, 고추장 3숟갈, 사이다 100mL", missed_material: "냉면사리 2인분, 삶은달걀 1개, 참기름 1숟갈"},
  {title: "돈까스 냉면", url: "http://haemukja.com/recipes/4822", image: "http://cloudfront.haemukja.com/vh.php?url=http://d1hk7gw6lgygff.cloudfront.net/uploads/direction/image_file/57485/pad_thumb_1.jpg&convert=jpgmin&rt=600", writer: "해먹남녀", subtitle: "#106. 돈냉의 시대가 왔다! 돈까스 냉면", serving: "1인 기준", recipe_material: "냉면사리 1인분, 냉면육수 1봉, 삶은계란 1/2개, 오이 1/5개, 무절임 3장, 돼지안심 130~150g, 계란 1개, 밀가루 4큰술, 빵가루 2/3컵, 고춧가루 2큰술, 설탕 1큰술, 식초 1큰술, 고추장 1큰술, 간장 1큰술", missed_material: "냉면사리 1인분, 냉면육수 1봉, 무절임 3장, 고춧가루 2큰술"},
  {title: "얼음비빔소바", url: "http://haemukja.com/recipes/2240", image: "http://cloudfront.haemukja.com/vh.php?url=http://d1hk7gw6lgygff.cloudfront.net/uploads/direction/image_file/32403/pad_thumb_0.JPG&convert=jpgmin&rt=600", writer: "해먹남녀", subtitle: "시원한 별미면요리, 얼음비빔소바", serving: "1인 기준", recipe_material: "소바면 120g, 우동소스 100mL, 꿀 1/2T", missed_material: "소바면 120g, 우동소스 100mL"},
  {title: "대패 삼겹살 냉채", url: "http://haemukja.com/recipes/904", image: "http://cloudfront.haemukja.com/vh.php?url=http://d1hk7gw6lgygff.cloudfront.net/uploads/direction/image_file/12078/pad_thumb_____.jpg&convert=jpgmin&rt=600", writer: "해먹남녀", subtitle: "무더운 여름날, 힘 빠지는 월요일 기운 돋우는 레시피 : 대패 삼겹살 냉채", serving: "2인 기준", recipe_material: "삼겹살 500g, 오이 1개, 대파 1줄기, 파프리카레드 1/2개, 옐로 1/2개, 어린잎채소 100g, 쌈무 4장, 홀그레인머스타드 1티스푼, 식초 100ml, 설탕 75g, 다진마늘 약간", missed_material: "파프리카레드 1/2개, 옐로 1/2개, 어린잎채소 100g, 쌈무 4장, 홀그레인머스타드 1티스푼, 다진마늘 약간"},
  {title: "칵테일 상그리아", url: "http://haemukja.com/recipes/991", image: "http://cloudfront.haemukja.com/vh.php?url=http://d1hk7gw6lgygff.cloudfront.net/uploads/direction/image_file/13544/pad_thumb_0___.JPG&convert=jpgmin&rt=600", writer: "해먹남녀", subtitle: "시원하게 여름을 보내는 방법", serving: "3인 기준", recipe_material: "레드와인 360mL, 오렌지 1개, 레몬 1개, 라임 1개, 사과 1/2개, 천도복숭아 1/2개, 데라웨어포도 1송이, 화이트와인 360mL, 오렌지 1개, 레몬 1개, 라임 1개, 자몽 1/2개, 사과 1/2개, 수박 8조각, 설탕 2큰술, 애플민트 약간, 얼음 1컵, 탄산수 1병", missed_material: "오렌지 1개, 데라웨어포도 1송이, 오렌지 1개, 탄산수 1병"},
])
RecipeProduct.create!([
  {recipe_id: 1, product_id: 292},
  {recipe_id: 1, product_id: 249},
  {recipe_id: 1, product_id: 474},
  {recipe_id: 1, product_id: 154},
  {recipe_id: 1, product_id: 726},
  {recipe_id: 1, product_id: 644},
  {recipe_id: 2, product_id: 717},
  {recipe_id: 2, product_id: 622},
  {recipe_id: 2, product_id: 599},
  {recipe_id: 3, product_id: 388},
  {recipe_id: 3, product_id: 359},
  {recipe_id: 3, product_id: 652},
  {recipe_id: 3, product_id: 652},
  {recipe_id: 3, product_id: 726},
  {recipe_id: 4, product_id: 430},
  {recipe_id: 4, product_id: 235},
  {recipe_id: 4, product_id: 284},
  {recipe_id: 4, product_id: 224},
  {recipe_id: 4, product_id: 660},
  {recipe_id: 4, product_id: 654},
  {recipe_id: 4, product_id: 690},
  {recipe_id: 4, product_id: 306},
  {recipe_id: 5, product_id: 383},
  {recipe_id: 5, product_id: 292},
  {recipe_id: 5, product_id: 282},
  {recipe_id: 5, product_id: 608},
  {recipe_id: 5, product_id: 647},
  {recipe_id: 5, product_id: 698},
  {recipe_id: 5, product_id: 660},
  {recipe_id: 5, product_id: 614},
  {recipe_id: 5, product_id: 609},
  {recipe_id: 5, product_id: 720},
  {recipe_id: 6, product_id: 478},
  {recipe_id: 6, product_id: 292},
  {recipe_id: 6, product_id: 431},
  {recipe_id: 6, product_id: 474},
  {recipe_id: 6, product_id: 6},
  {recipe_id: 6, product_id: 12},
  {recipe_id: 6, product_id: 690},
  {recipe_id: 6, product_id: 647},
  {recipe_id: 6, product_id: 609},
  {recipe_id: 6, product_id: 660},
  {recipe_id: 7, product_id: 615},
  {recipe_id: 8, product_id: 430},
  {recipe_id: 8, product_id: 292},
  {recipe_id: 8, product_id: 224},
  {recipe_id: 8, product_id: 647},
  {recipe_id: 8, product_id: 690},
  {recipe_id: 9, product_id: 714},
  {recipe_id: 9, product_id: 357},
  {recipe_id: 9, product_id: 352},
  {recipe_id: 9, product_id: 378},
  {recipe_id: 9, product_id: 393},
  {recipe_id: 9, product_id: 737},
  {recipe_id: 9, product_id: 357},
  {recipe_id: 9, product_id: 352},
  {recipe_id: 9, product_id: 390},
  {recipe_id: 9, product_id: 378},
  {recipe_id: 9, product_id: 383},
  {recipe_id: 9, product_id: 690},
  {recipe_id: 9, product_id: 652},
  {recipe_id: 9, product_id: 726},
])
